include(ExternalProject)

ExternalProject_Add(assimp
    PREFIX assimp
    GIT_REPOSITORY https://github.com/assimp/assimp.git
    GIT_TAG v5.0.0
    CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${EXTERNAL_INSTALL_LOCATION}/assimp
        #-DBUILD_SHARED_LIBS=OFF
		-DCMAKE_RUNTIME_OUTPUT_DIRECTORY=${CMAKE_RUNTIME_OUTPUT_DIRECTORY}
		-DASSIMP_BUILD_TESTS=OFF
        -DOpenGL_GL_PREFERENCE=GLVND
        -DASSIMP_BUILD_ASSIMP_TOOLS=OFF
        -DASSIMP_BUILD_ZLIB=ON
        -DASSIMP_NO_EXPORT=ON
        -DASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT=OFF
        -DASSIMP_BUILD_GLTF_IMPORTER=TRUE
        -DASSIMP_BUILD_OGRE_IMPORTER=TRUE # Contains common Animation namespace
)


set(ASSIMP_INCLUDE ${EXTERNAL_INSTALL_LOCATION}/assimp/include)

if (NOT ${CMAKE_BUILD_TYPE} MATCHES "Release")
	set (WIN_LIB_SUFFIX "d")
endif()



if(WIN32 AND MSVC)
set(ASSIMP_LIB 
    ${EXTERNAL_INSTALL_LOCATION}/assimp/lib/assimp-vc${MSVC_TOOLSET_VERSION}-mt${WIN_LIB_SUFFIX}${CMAKE_STATIC_LIBRARY_SUFFIX} # not sure how these names are generated....   
    ${EXTERNAL_INSTALL_LOCATION}/assimp/lib/IrrXML${WIN_LIB_SUFFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
    ${EXTERNAL_INSTALL_LOCATION}/assimp/lib/zlibstatic${WIN_LIB_SUFFIX}${CMAKE_STATIC_LIBRARY_SUFFIX})
else()
set(ASSIMP_LIB 
    ${EXTERNAL_INSTALL_LOCATION}/assimp/lib/libassimp${CMAKE_STATIC_LIBRARY_SUFFIX}    
    ${EXTERNAL_INSTALL_LOCATION}/assimp/lib/libIrrXML${CMAKE_STATIC_LIBRARY_SUFFIX}
    ${EXTERNAL_INSTALL_LOCATION}/assimp/lib/libzlibstatic${CMAKE_STATIC_LIBRARY_SUFFIX})
endif()
