# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:

- script: mkdir build && cd build
  displayName: 'go to build'

- task: CMake@1
  inputs:
    cmakeArgs: -G "Visual Studio 16 2019" ..

- task: CMake@1
  inputs:
      cmakeArgs: --build .

